name: 🌠 nightly

on: [ push ]
  #  schedule:
  #  - cron:  '0 0 * * *'

jobs:
  build-avahi-utils-image:
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: ⚙ Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: ⚙ Setup Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest

      - name: 🔓 Authenticate docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🛠 Build image
        run: |
          DOCKER_BUILD="docker buildx build --platform linux/amd64,linux/arm64 --push" \
            ORG="${{ secrets.DOCKERHUB_USERNAME }}" \
            DOCKER_BUILDKIT=1 script/build --avahi-utils-image

  build-chip-environment-image:
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: ⚙ Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: ⚙ Setup Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest

      - name: 🔓 Authenticate docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🛠 Build image
        run: |
          DOCKER_BUILD='docker buildx build --platform linux/amd64,linux/arm64 --push' \
            ORG="${{ secrets.DOCKERHUB_USERNAME }}" \
            DOCKER_BUILDKIT=1 script/build --chip-environment-image

  build-otbr-image:
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: ⚙ Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: ⚙ Setup Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest

      - name: 🔓 Authenticate docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🥾 Bootstrap
        run: script/bootstrap --ot-br-posix

      - name: 🛠 Build image
        run: |
          DOCKER_BUILD="docker buildx build --platform linux/amd64,linux/arm64 --push" \
            ORG="${{ secrets.DOCKERHUB_USERNAME }}" \
            DOCKER_BUILDKIT=1 script/build --otbr-image

  build-ot-commissioner-image:
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: ⚙ Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: ⚙ Setup Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest

      - name: 🔓 Authenticate docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🥾 Bootstrap
        run: script/bootstrap --ot-commissioner

      - name: 🛠 Build image
        run: |
          DOCKER_BUILD="docker buildx build --platform linux/amd64,linux/arm64 --push" \
            ORG="${{ secrets.DOCKERHUB_USERNAME }}" \
            DOCKER_BUILDKIT=1 script/build --ot-commissioner-image

  build-ot-nrf528xx-environment-image:
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: ⚙ Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: ⚙ Setup Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest

      - name: 🔓 Authenticate docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🥾 Bootstrap
        run: script/bootstrap --ot-nrf528xx

      - name: 🛠 Build image
        run: |
          DOCKER_BUILD='docker buildx build --platform linux/amd64,linux/arm64 --push' \
            ORG=${{ secrets.DOCKERHUB_USERNAME }} \
            DOCKER_BUILDKIT=1 script/build --ot-nrf528xx-environment-image

  build-nrfconnect-chip-environment-image:
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: ⚙ Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: ⚙ Setup Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest

      - name: 🔓 Authenticate docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🥾 Bootstrap
        run: script/bootstrap --nrfconnect-chip

      - name: 🛠 Build image
        run: |
            DOCKER_BUILD='docker buildx build --platform linux/amd64,linux/arm64 --push' \
              ORG="${{ secrets.DOCKERHUB_USERNAME }}" \
              DOCKER_BUILDKIT=1 script/build \
              --nrfconnect-toolchain-image \
              --nrfconnect-chip-environment-image

  build-nrfutil-image:
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: ⚙ Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: ⚙ Setup Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest

      - name: 🔓 Authenticate docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🛠 Build image
        run: |
            DOCKER_BUILD="docker buildx build --platform linux/amd64,linux/arm64 --push" \
              ORG="${{ secrets.DOCKERHUB_USERNAME }}" \
              DOCKER_BUILDKIT=1 script/build --nrfutil-image

  build-nrf52840-dongle-ot-rcp:
    needs:
      - build-ot-nrf528xx-environment-image
      - build-nrfutil-image
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: 🥾 Bootstrap
        run: script/bootstrap --ot-nrf528xx

      - name: 🛠 Build artifact
        run: ORG="${{ secrets.DOCKERHUB_USERNAME }}" script/build --nrf52840-dongle-ot-rcp

      - name: ⬆ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nrf52840-dongle-ot-rcp
          path: build/Release/nrf52840-dongle-ot-rcp.zip

  build-nrf52840-dongle-thread-lighting-app-latest:
    needs:
      - build-nrfconnect-chip-environment-image
      - build-nrfutil-image
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: 🥾 Bootstrap
        run: script/bootstrap --chip

      - name: 🛠 Build artifact
        run: ORG="${{ secrets.DOCKERHUB_USERNAME }}" script/build --nrf52840-dongle-thread-lighting-app

      - name: 🔖 Rename artifact
        run: mv nrf52840-dongle-thread-lighting-app.zip nrf52840-dongle-thread-lighting-app-LATEST.zip
        working-directory: build/Release

      - name: ⬆ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nrf52840-dongle-thread-lighting-app-latest
          path: build/Release/nrf52840-dongle-thread-lighting-app-LATEST.zip

  build-nrf52840-dongle-thread-lighting-app-test_event:
    needs:
      - build-nrfconnect-chip-environment-image
      - build-nrfutil-image
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: 🥾 Bootstrap
        run: script/bootstrap --chip test_event_6

      - name: 🛠 Build artifact
        run: ORG="${{ secrets.DOCKERHUB_USERNAME }}" script/build --nrf52840-dongle-thread-lighting-app

      - name: 🔖 Rename artifact
        run: mv nrf52840-dongle-thread-lighting-app.zip nrf52840-dongle-thread-lighting-app-TEST_EVENT_6.zip
        working-directory: build/Release

      - name: ⬆ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nrf52840-dongle-thread-lighting-app-test_event
          path: build/Release/nrf52840-dongle-thread-lighting-app-TEST_EVENT_6.zip

  build-chip-device-ctrl-x86_64-latest:
    needs:
      - build-chip-environment-image
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: 🥾 Bootstrap
        run: script/bootstrap --chip

      - name: 🛠 Build artifact
        run: ORG="${{ secrets.DOCKERHUB_USERNAME }}" script/build --chip-device-ctrl

      - name: 🗃 Archive artifact
        run: tar -cJf chip-device-ctrl-x86_64-LATEST.tar.xz --owner=0 --group=0 chip-device-ctrl
        working-directory: build/Release

      - name: ⬆ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chip-device-ctrl-x86_64-latest
          path: build/Release/chip-device-ctrl-x86_64-LATEST.tar.xz

  build-chip-device-ctrl-aarch64-latest:
    needs:
      - build-chip-environment-image
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: ⚙ Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: 🥾 Bootstrap
        run: script/bootstrap --chip

      - name: ⬇ Pull builder image
        run: docker pull --platform linux/aarch64 ${{ secrets.DOCKERHUB_USERNAME }}/chip-environment:latest

      - name: 🛠 Build artifact
        run: ORG="${{ secrets.DOCKERHUB_USERNAME }}" script/build --chip-device-ctrl

      - name: 🗃 Archive artifact
        run: tar -cJf chip-device-ctrl-aarch64-LATEST.tar.xz --owner=0 --group=0 chip-device-ctrl
        working-directory: build/Release

      - name: ⬆ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chip-device-ctrl-aarch64-latest
          path: build/Release/chip-device-ctrl-aarch64-LATEST.tar.xz

  build-chip-device-ctrl-x86_64-test_event:
    needs:
      - build-chip-environment-image
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: 🥾 Bootstrap
        run: script/bootstrap --chip test_event_6

      - name: 🛠 Build artifact
        run: ORG="${{ secrets.DOCKERHUB_USERNAME }}" script/build --chip-device-ctrl

      - name: 🗃 Archive artifact
        run: tar -cJf chip-device-ctrl-x86_64-TEST_EVENT_6.tar.xz --owner=0 --group=0 chip-device-ctrl
        working-directory: build/Release

      - name: ⬆ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chip-device-ctrl-x86_64-test_event
          path: build/Release/chip-device-ctrl-x86_64-TEST_EVENT_6.tar.xz

  build-chip-device-ctrl-aarch64-test_event:
    needs:
      - build-chip-environment-image
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: ⚙ Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: 🥾 Bootstrap
        run: script/bootstrap --chip test_event_6

      - name: ⬇ Pull builder image
        run: docker pull --platform linux/aarch64 ${{ secrets.DOCKERHUB_USERNAME }}/chip-environment:latest

      - name: 🛠 Build artifact
        run: ORG="${{ secrets.DOCKERHUB_USERNAME }}" script/build --chip-device-ctrl

      - name: 🗃 Archive artifact
        run: tar -cJf chip-device-ctrl-aarch64-TEST_EVENT_6.tar.xz --owner=0 --group=0 chip-device-ctrl
        working-directory: build/Release

      - name: ⬆ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chip-device-ctrl-aarch64-test_event
          path: build/Release/chip-device-ctrl-aarch64-TEST_EVENT_6.tar.xz

  publish-release:
    needs:
      - build-nrf52840-dongle-ot-rcp
      - build-nrf52840-dongle-thread-lighting-app-latest
      - build-nrf52840-dongle-thread-lighting-app-test_event
      - build-chip-device-ctrl-x86_64-latest
      - build-chip-device-ctrl-aarch64-latest
      - build-chip-device-ctrl-x86_64-test_event
      - build-chip-device-ctrl-aarch64-test_event
    runs-on: ubuntu-latest
    steps:
      - name: 📆 Get date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%d')"
        id: date

      - name: ⬇ Download artifacts
        uses: actions/download-artifact@v2
        with:
           path: artifacts

      - name: ↩ Flatten artifacts
        run: |
          find artifacts -type f -exec mv {} artifacts \;
          find artifacts -depth -exec rmdir {} \;
          ls -laR

      - name: 🗑 Delete current nightly
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Publish nightly
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.date.outputs.date }}
          file: artifacts/*
          tag: nightly
          file_glob: true
          overwrite: true
