name: NRFCONNECT-CHIP

on:
  push:
    # branches: [ chore/submodule-cleanup ]
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: ./scripts/setup -u -o NRFCONNECT_CHIP_DOCKER
      - run: |
          DOCKER_BUILD="docker buildx build --platform linux/amd64,linux/arm64 --push" \
            ORG="${{ secrets.DOCKER_USERNAME }}" \
            VERSION=latest \
            DOCKER_BUILDKIT=1 ./scripts/docker-build --nrfconnect-chip
