name: OT-NRF528XX-ENVIRONMENT

on:
  push:
    branches: [ chore/submodule-cleanup ]

jobs:
  dockerhub-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: ./scripts/setup -u -o OT_NRF528XX
      - run: |
          DOCKER_BUILD='docker buildx build --platform linux/amd64,linux/arm64 --push' \
            ORG=${{ secrets.DOCKERHUB_USERNAME }} \
            VERSION=latest \
            DOCKER_BUILDKIT=1 ./scripts/docker-build --ot-nrf528xx-environment

  build:
    needs: [dockerhub-publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/setup -u -o OT_NRF528XX
      - run: |
          docker run --rm \
           -v $PWD/third_party/ot-nrf528xx:/ot-nrf528xx \
           -v $PWD/build/ot-nrf528xx:/ot-nrf528xx/build \
           -w /ot-nrf528xx \
           ${{ secrets.DOCKERHUB_USERNAME }}/ot-nrf528xx-environment:latest /bin/bash -c \
          './script/bootstrap && script/build nrf52840 USB_trans -DOT_BOOTLOADER=USB -DOT_THREAD_VERSION=1.2 && arm-none-eabi-objcopy -O ihex build/bin/ot-rcp build/bin/ot-rcp.hex'
