name: OT-NRF528XX-ENVIRONMENT

on:
  push:
    branches: [ chore/submodule-cleanup ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: echo "THIRD_PARTY_HASH=${{ hashFiles('.thirdParty') }}" >> $GITHUB_ENV
      - run: ./scripts/setup -u -o OT_NRF528XX
      # - if: ${{ env.THIRD_PARTY_HASH != hashFiles('.thirdParty') }}
      - run: |
          DOCKER_BUILD="docker buildx build --platform linux/amd64,linux/arm64 --push" \
            ORG="${{ secrets.DOCKER_USERNAME }}" \
            VERSION=latest \
            DOCKER_BUILDKIT=1 ./scripts/docker-build --ot-nrf528xx-environment
