name: shellcheck

on:
  push:
    branches: [ chore/submodule-cleanup ]
#on: [pull_request]

jobs:
  shellcheck-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: 'script'
        env:
          SHELLCHECK_OPTS: -e SC1008 -e SC2096 -s bash

  shellcheck-docker-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: 'etc/docker'
        env:
          SHELLCHECK_OPTS: -e SC1008 -e SC2096 -s bash
